# Molecule Dockerfile Jinja2 template for ansible-role-install-ros-ubuntu

#
#   This section is dynamically populated with the content
#   of the `platforms` items from the `molecule.yml` file
#
{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

ENV SUDO_GROUP=sudo

RUN if [ $(command -v apt-get) ]; then \
    apt-get update \
    && \
    apt-get install -y --no-install-recommends \
    python3 \
    sudo \
    bash \
    ca-certificates \
    iproute2 \
    init \
    && \
    apt-get clean; \
    fi

RUN set -xe; \
    if [ -n "${ANSIBLE_USER}" ]; then \
    groupadd -r "${ANSIBLE_USER}" \
    && \
    useradd -m -g "${ANSIBLE_USER}" "${ANSIBLE_USER}" \
    && \
    usermod -aG "${SUDO_GROUP}" "${ANSIBLE_USER}" \
    && \
    sed -i "/^%${SUDO_GROUP}/s/ALL\$/NOPASSWD:ALL/g" /etc/sudoers; \
    fi
